#!/bin/sh
export XDG_SESSION_TYPE=wayland
export XKB_DEFAULT_LAYOUT="latam"
export MOZ_ENABLE_WAYLAND=1
export _JAVA_AWT_WM_NONREPARENTING=1
#export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=qt6ct:qt5ct
export XDG_CURRENT_DESKTOP=sway
export GTK_THEME=Materia-dark-compact:dark
