filetype indent on
set mouse=a
set tabstop=2
set cindent tabstop=2
set shiftwidth=2
set cindent shiftwidth=2
set incsearch
set number
set autoindent
set smartindent
syntax on
set background=dark

call plug#begin()
" List your plugins here
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'honza/vim-snippets'
Plug 'garbas/vim-snipmate'
Plug 'MarcWeber/vim-addon-mw-utils'
call plug#end()
